### PR TITLE
Support `hedgehog-1.2`

### LINKED ISSUE #61: Support Hedgehog Skipping
The next version of Hedgehog will have "skipping" (https://github.com/hedgehogqa/haskell-hedgehog/pull/454). It will also break `Internal` APIs that we depend on.

We should at least upgrade to build successfully with the new version, and it would be good to support the skipping functionality as well. @mbg Would you like to have a go at this? I could do the former option myself but don't have time for the latter.

### PR DESCRIPTION
**Pull request by mbg**
Support `hedgehog-1.2` and resolve #61.

### CODE REVIEW

**Comment by gwils** [comment]
>might want to release #62 as a point release before this

I reckon we probably should, since this upcoming version will be a big cut-off point, at which some people will find themselves stuck.

Edit: Would you like to do this, or should I? I'm happy to.

>CI failures, CPP

I would prefer us to support all GHC versions that our hedgehog  bounds support, but I don't think it's worth the extra effort of adding CPP to support older hedgehog versions (and thereby older GHC versions). If someone needs to use an older version of hedgehog, they can use an older versions of tasty-hedgehog too.

**Comment by mbg** [comment]
@gwils I have pushed a version bump to `1.3.1` to `master` and uploaded a [candidate release](https://hackage.haskell.org/package/tasty-hedgehog-1.3.1.0/candidate) for the changes from #62.

**Comment by gwils** [comment]
Thank you! Feel free to release.

**Comment by spacekitteh** [comment]
What's stopping this from merging now that #62 is merged?

**Comment by mbg** [comment]
Ah sorry, I think I was working on releasing this after I released the changes from #62 and got distracted by something. I will finish it now.

**Comment by mbg** [comment]
@gwils this should be all good now. I have also uploaded a package candidate at https://hackage.haskell.org/package/tasty-hedgehog-1.4.0.0/candidate -- would be good to have someone sanity check that this all fine!

**Comment by ocharles** [comment]
I can give this a try on Monday if you don't mind waiting until then

**Comment by ocharles** [comment]
Alas, I can't easily test this right now because I need to upgrade `hedgehog-classes` in order to upgrade to Hedgehog 1.2 at work.

**Comment by gwils** [comment]
I have run the test suite on this branch on all the GHC versions we support, and they passed. I've asked a friend to test this version on his project.

**Comment by JackKelly-Bellroy** [comment]
We have a couple of packages that make light use `tasty-hedgehog`, and I was able to build and run their tests using 1609b3141709942e72be035c0fc68aa00c5cb733 (the current target of `feature/skipping`).

This was with GHC 9.2.4.

**Comment by JackKelly-Bellroy** [comment]
Actually, we have more than a couple, since `tasty-discover` seems to use it under the hood.

**Comment by mbg** [comment]
It seems like this is probably good to merge, so I will do that now and release `1.4` on Hackage.

**Pull request merged**
