### PR TITLE
Updates for GHC-8.8.1

### PR DESCRIPTION
**Pull request by sjakobi**
* Bump upper bound for base
* Add GHC-8.8.1 to "tested-with" section
* Regenerate .travis.yml

This patch is a bit premature – at least happy, hedgehog and tasty-expected-failure will need fresh releases before this can pass CI.

### CODE REVIEW

**Comment by chshersh** [comment]
@sjakobi Thanks for the PR! Are you aware of the plans in `hedgehog` to support GHC-8.8.1?

**Comment by sjakobi** [comment]
> Are you aware of the plans in hedgehog to support GHC-8.8.1?

I have opened https://github.com/hedgehogqa/haskell-hedgehog/issues/317.

`tasty-expected-failure` has a compatible release now.

**Comment by chshersh** [comment]
`hedgehog-1.0.1` was released which supports GHC-8.8.

**Comment by sjakobi** [comment]
> `hedgehog-1.0.1` was released which supports GHC-8.8.

Great! I think this PR should be good to merge then. :)

**Pull request merged**
