### PR TITLE
Ease bounds on tasty and mark point release.

### PR DESCRIPTION
**Pull request by decentral1se**
Deal with bounds part of https://github.com/qfpl/tasty-hedgehog/issues/4.

Follows from https://github.com/lwm/tasty-discover/issues/131.

### CODE REVIEW

**Comment by decentral1se** [comment]
If someone could take a look at this soon and make a release, I'll re-enable the blocked packages on stackage.

**Comment by dalaing** [comment]
I think the bounds for tasty need to be between 1.0 and 1.1, otherwise LGTM.

**Comment by decentral1se** [comment]
Updated! Thanks for reviewing @dalaing.

**Review by dalaing — APPROVED** [review]
LGTM - thanks!

**Comment by decentral1se** [comment]
Nice one!

**Pull request merged**
