### PR TITLE
Update for hedgehog-0.5 + misc improvements

### PR DESCRIPTION
**Pull request by LightAndLight**
@dalaing 

What else needs to be done before this can go live?

### CODE REVIEW

**Comment by dalaing** [comment]
I'd like to bring default.nix and shell.nix into line with the output from cabal2nix / the nix style from the nixpkgs manual (those two tend to be in agreement).

Other than that - should we add some tests?  Something like the properties for a reverse function, for a) actual reverse and b) a busted reverse, just so that we have something we can run to confirm that it all  works.

**Review by dalaing — CHANGES_REQUESTED** [review]
I'd like to bring default.nix and shell.nix into line with the output from cabal2nix / the nix style from the nixpkgs manual (those two tend to be in agreement).

Other than that - should we add some tests? Something like the properties for a reverse function, for a) actual reverse and b) a busted reverse, just so that we have something we can run to confirm that it all works.

Should we add haddocks for the various top level definitions?

**Review by dalaing — APPROVED** [review]

**Comment by LightAndLight** [comment]
Also let it be known that colored output does work, it's just that `cabal test` removes it. Not sure if there's a way to get around that.

**Comment by dalaing** [comment]
Awesome 👍

**Comment by MichaelXavier** [comment]
Cool! So are we go for launch?

**Comment by dalaing** [comment]
I think we are, unless I've forgotten something.

**Comment by dalaing** [comment]
That wasn't a very useful comment from me.  Unless someone has a reason why we shouldn't, or work we should do first, I think we should push this to Hackage.  I think someone from QFPL will take care of that today or tomorrow.

**Comment by dalaing** [comment]
We are gone for launch: https://hackage.haskell.org/package/tasty-hedgehog :)

**Pull request merged**
