### PR TITLE
Make it build with ghc 9.10

### PR DESCRIPTION
**Pull request by erikd**
Had to add a `cabal.project` file containing a `source-repository-package` stanza linking to a `hedgehog` PR.

### CODE REVIEW

**Comment by erikd** [comment]
`hedgehog` has been updated in Hackage so the temporary `cabal.project` file can be removed.

Ready for review.

**Review by mbg — APPROVED** [review]
These changes make sense to me -- thank you for looking at this! I have approved the workflow runs and am happy to merge this if they succeed.

**Comment by erikd** [comment]
Would also appreciate a Hackage metadata edit.

**Comment by mbg** [comment]
No problem - I have published a new metadata revision which adjusts the upper bound for `base` according to this PR.

**Pull request merged**
